# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain Java versions, and provides a first line of defence against bad commits.

name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [
            "17" # Latest version
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Jar Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: build/libs/
      - name: Create MultiMC Instance
        run: cd scripts; ./multimc.sh
      - name: Upload MultiMC Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: multimc
          path: scripts/bungleware*.zip
